# Generated by Django 4.1 on 2024-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='passcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
